-- CreateTable
CREATE TABLE "InternProfile" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "paymentPageTitle" TEXT,
    "paymentDate" DATETIME,
    "registrationAmount" REAL,
    "phone" TEXT,
    "gender" TEXT,
    "state" TEXT,
    "branch" TEXT,
    "yearOfPassingOut" TEXT,
    "internshipProgram" TEXT,
    "technology" TEXT,
    "startDate" DATETIME,
    "timings" TEXT,
    "duration" TEXT,
    "venuePreference" TEXT,
    "referredPersonName" TEXT,
    "internshipId" TEXT,
    "studentComingDate" DATETIME,
    "officeInDate" DATETIME,
    "studentStatus" TEXT,
    "studentRemarks" TEXT,
    "offerLetter" TEXT,
    "idCard" TEXT,
    "welcomeKit" TEXT,
    "totalPayment" REAL,
    "registrationPayment" REAL,
    "discount" REAL,
    "balance" REAL DEFAULT 421000,
    "installment1" REAL DEFAULT 0,
    "installDate1" DATETIME,
    "paymentMode" TEXT,
    "installment2" REAL DEFAULT 0,
    "dateOfFullPayment" DATETIME,
    "totalPaymentMode" TEXT,
    "balanceAfterInstallments" REAL,
    "cashAmount" REAL,
    "classTimings" TEXT,
    "attendance" TEXT,
    "assignments" TEXT,
    "projectTitle" TEXT,
    "internshipCompletionCertificate" TEXT,
    "projectCompletionCertificate" TEXT,
    "exitDate" DATETIME,
    "remarks" TEXT,
    CONSTRAINT "InternProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "InternProfile_userId_key" ON "InternProfile"("userId");
